export const comuni = [
  "Macello",
  "Maglione",
  "Marentino",
  "Massello",
  "Mathi",
  "Mattie",
  "Mazz\u00e8",
  "Meana di Susa",
  "Mercenasco",
  "Mezzenile",
  "Mombello di Torino",
  "Mompantero",
  "Monastero di Lanzo",
  "Moncalieri",
  "Moncenisio",
  "Montaldo Torinese",
  "Montalenghe",
  "Montalto Dora",
  "Montanaro",
  "Monteu da Po",
  "Moriondo Torinese",
  "Mappano",
  "Mollia",
  "Moncrivello",
  "Motta de' Conti",
  "Maggiora",
  "Mandello Vitta",
  "Marano Ticino",
  "Massino Visconti",
  "Meina",
  "Mezzomerico",
  "Miasino",
  "Momo",
  "Macra",
  "Magliano Alfieri",
  "Magliano Alpi",
  "Mango",
  "Manta",
  "Marene",
  "Margarita",
  "Marmora",
  "Marsaglia",
  "Martiniana Po",
  "Melle",
  "Moiola",
  "Mombarcaro",
  "Mombasiglio",
  "Monastero di Vasco",
  "Monasterolo Casotto",
  "Monasterolo di Savigliano",
  "Monchiero",
  "Mondov\u00ec",
  "Monesiglio",
  "Monforte d'Alba",
  "Mont\u00e0",
  "Montaldo di Mondov\u00ec",
  "Montaldo Roero",
  "Montanera",
  "Montelupo Albese",
  "Montemale di Cuneo",
  "Monterosso Grana",
  "Monteu Roero",
  "Montezemolo",
  "Monticello d'Alba",
  "Moretta",
  "Morozzo",
  "Murazzano",
  "Murello",
  "Maranzana",
  "Maretto",
  "Moasca",
  "Mombaldone",
  "Mombaruzzo",
  "Mombercelli",
  "Monale",
  "Monastero Bormida",
  "Moncalvo",
  "Moncucco Torinese",
  "Mongardino",
  "Montabone",
  "Montafia",
  "Montaldo Scarampi",
  "Montechiaro d'Asti",
  "Montegrosso d'Asti",
  "Montemagno",
  "Moransengo",
  "Montiglio Monferrato",
  "Malvicino",
  "Masio",
  "Melazzo",
  "Merana",
  "Mirabello Monferrato",
  "Molare",
  "Molino dei Torti",
  "Mombello Monferrato",
  "Momperone",
  "Moncestino",
  "Mongiardino Ligure",
  "Monleale",
  "Montacuto",
  "Montaldeo",
  "Montaldo Bormida",
  "Montecastello",
  "Montechiaro d'Acqui",
  "Montegioco",
  "Montemarzino",
  "Morano sul Po",
  "Morbello",
  "Mornese",
  "Morsasco",
  "Murisengo",
  "Magnano",
  "Massazza",
  "Masserano",
  "Mezzana Mortigliengo",
  "Miagliano",
  "Mongrando",
  "Mottalciata",
  "Muzzano",
  "Macugnaga",
  "Madonna del Sasso",
  "Malesco",
  "Masera",
  "Massiola",
  "Mergozzo",
  "Miazzina",
  "Montecrestese",
  "Montescheno",
  "Montjovet",
  "Morgex",
  "Malgesso",
  "Malnate",
  "Marchirolo",
  "Marnate",
  "Marzio",
  "Masciago Primo",
  "Mercallo",
  "Mesenzana",
  "Montegrino Valtravaglia",
  "Monvalle",
  "Morazzone",
  "Mornago",
  "Maccagno con Pino e Veddasca",
  "Magreglio",
  "Mariano Comense",
  "Maslianico",
  "Menaggio",
  "Merone",
  "Moltrasio",
  "Monguzzo",
  "Montano Lucino",
  "Montemezzo",
  "Montorfano",
  "Mozzate",
  "Musso",
  "Madesimo",
  "Mantello",
  "Mazzo di Valtellina",
  "Mello",
  "Mese",
  "Montagna in Valtellina",
  "Morbegno",
  "Magenta",
  "Magnago",
  "Marcallo con Casone",
  "Masate",
  "Mediglia",
  "Melegnano",
  "Melzo",
  "Mesero",
  "Milano",
  "Morimondo",
  "Motta Visconti",
  "Madone",
  "Mapello",
  "Martinengo",
  "Mezzoldo",
  "Misano di Gera d'Adda",
  "Moio de' Calvi",
  "Monasterolo del Castello",
  "Montello",
  "Morengo",
  "Mornico al Serio",
  "Mozzanica",
  "Mozzo",
  "Medolago",
  "Maclodio",
  "Magasa",
  "Mairano",
  "Malegno",
  "Malonno",
  "Manerba del Garda",
  "Manerbio",
  "Marcheno",
  "Marmentino",
  "Marone",
  "Mazzano",
  "Milzano",
  "Moniga del Garda",
  "Monno",
  "Monte Isola",
  "Monticelli Brusati",
  "Montichiari",
  "Montirone",
  "Mura",
  "Muscoline",
  "Magherno",
  "Marcignago",
  "Marzano",
  "Mede",
  "Menconico",
  "Mezzana Bigli",
  "Mezzana Rabattone",
  "Mezzanino",
  "Miradolo Terme",
  "Montalto Pavese",
  "Montebello della Battaglia",
  "Montecalvo Versiggia",
  "Montescano",
  "Montesegale",
  "Monticelli Pavese",
  "Mont\u00f9 Beccaria",
  "Mornico Losana",
  "Mortara",
  "Madignano",
  "Malagnino",
  "Martignana di Po",
  "Monte Cremasco",
  "Montodine",
  "Moscazzano",
  "Motta Baluffi",
  "Magnacavallo",
  "Mantova",
  "Marcaria",
  "Mariana Mantovana",
  "Marmirolo",
  "Medole",
  "Moglia",
  "Monzambano",
  "Motteggiana",
  "Malgrate",
  "Mandello del Lario",
  "Margno",
  "Merate",
  "Missaglia",
  "Moggio",
  "Molteno",
  "Monte Marenzo",
  "Montevecchia",
  "Monticello Brianza",
  "Morterone",
  "Maccastorna",
  "Mairago",
  "Maleo",
  "Marudo",
  "Massalengo",
  "Meleti",
  "Merlino",
  "Montanaso Lombardo",
  "Mulazzano",
  "Macherio",
  "Meda",
  "Mezzago",
  "Misinto",
  "Monza",
  "Muggi\u00f2",
  "Magr\u00e8 sulla strada del vino",
  "Malles Venosta",
  "Marebbe",
  "Marlengo",
  "Martello",
  "Meltina",
  "Merano",
  "Monguelfo-Tesido",
  "Montagna",
  "Moso in Passiria",
  "Mal\u00e9",
  "Massimeno",
  "Mazzin",
  "Mezzana",
  "Mezzano",
  "Mezzocorona",
  "Mezzolombardo",
  "Moena",
  "Molveno",
  "Mori",
  "Madruzzo",
  "Malcesine",
  "Marano di Valpolicella",
  "Mezzane di Sotto",
  "Minerbe",
  "Montecchia di Crosara",
  "Monteforte d'Alpone",
  "Mozzecane",
  "Malo",
  "Marano Vicentino",
  "Marostica",
  "Montebello Vicentino",
  "Montecchio Maggiore",
  "Montecchio Precalcino",
  "Monte di Malo",
  "Montegalda",
  "Montegaldella",
  "Monteviale",
  "Monticello Conte Otto",
  "Montorso Vicentino",
  "Mussolente",
  "Mansu\u00e8",
  "Mareno di Piave",
  "Maser",
  "Maserada sul Piave",
  "Meduna di Livenza",
  "Miane",
  "Mogliano Veneto",
  "Monastier di Treviso",
  "Monfumo",
  "Montebelluna",
  "Morgano",
  "Moriago della Battaglia",
  "Motta di Livenza",
  "Marcon",
  "Martellago",
  "Meolo",
  "Mira",
  "Mirano",
  "Musile di Piave",
  "Maser\u00e0 di Padova",
  "Masi",
  "Massanzago",
  "Megliadino San Vitale",
  "Merlara",
  "Mestrino",
  "Monselice",
  "Montagnana",
  "Montegrotto Terme",
  "Melara",
  "Magnano in Riviera",
  "Majano",
  "Malborghetto Valbruna",
  "Manzano",
  "Marano Lagunare",
  "Martignacco",
  "Mereto di Tomba",
  "Moggio Udinese",
  "Moimacco",
  "Montenars",
  "Mortegliano",
  "Moruzzo",
  "Muzzana del Turgnano",
  "Mariano del Friuli",
  "Medea",
  "Monfalcone",
  "Moraro",
  "Mossa",
  "Monrupino",
  "Muggia",
  "Maniago",
  "Meduno",
  "Montereale Valcellina",
  "Morsano al Tagliamento",
  "Mendatica",
  "Molini di Triora",
  "Montegrosso Pian Latte",
  "Montalto Carpasio",
  "Magliolo",
  "Mallare",
  "Massimino",
  "Millesimo",
  "Mioglia",
  "Murialdo",
  "Masone",
  "Mele",
  "Mezzanego",
  "Mignanego",
  "Moconesi",
  "Moneglia",
  "Montebruno",
  "Montoggio",
  "Maissana",
  "Monterosso al Mare",
  "Monticelli d'Ongina",
  "Morfasso",
  "Medesano",
  "Monchio delle Corti",
  "Montechiarugolo",
  "Montecchio Emilia",
  "Maranello",
  "Marano sul Panaro",
  "Medolla",
  "Mirandola",
  "Modena",
  "Montecreto",
  "Montefiorino",
  "Montese",
  "Malalbergo",
  "Marzabotto",
  "Medicina",
  "Minerbio",
  "Molinella",
  "Monghidoro",
  "Monterenzio",
  "Monte San Pietro",
  "Monzuno",
  "Mordano",
  "Masi Torello",
  "Mesola",
  "Massa Lombarda",
  "Meldola",
  "Mercato Saraceno",
  "Modigliana",
  "Montiano",
  "Misano Adriatico",
  "Mondaino",
  "Montefiore Conca",
  "Montegridolfo",
  "Morciano di Romagna",
  "Maiolo",
  "Montescudo-Monte Colombo",
  "Montecopiolo",
  "Massa",
  "Montignoso",
  "Mulazzo",
  "Massarosa",
  "Minucciano",
  "Molazzana",
  "Montecarlo",
  "Marliana",
  "Massa e Cozzile",
  "Monsummano Terme",
  "Montale",
  "Montecatini-Terme",
  "Marradi",
  "Montaione",
  "Montelupo Fiorentino",
  "Montespertoli",
  "Marciana",
  "Marciana Marina",
  "Montecatini Val di Cecina",
  "Montescudaio",
  "Monteverdi Marittimo",
  "Montopoli in Val d'Arno",
  "Marciano della Chiana",
  "Montemignaio",
  "Monterchi",
  "Monte San Savino",
  "Montevarchi",
  "Montepulciano",
  "Monteriggioni",
  "Monteroni d'Arbia",
  "Monticiano",
  "Murlo",
  "Montalcino",
  "Magliano in Toscana",
  "Manciano",
  "Massa Marittima",
  "Monte Argentario",
  "Montieri",
  "Monterotondo Marittimo",
  "Montemurlo",
  "Magione",
  "Marsciano",
  "Massa Martana",
  "Monte Castello di Vibio",
  "Montefalco",
  "Monteleone di Spoleto",
  "Monte Santa Maria Tiberina",
  "Montone",
  "Montecastrilli",
  "Montecchio",
  "Montefranco",
  "Montegabbione",
  "Monteleone d'Orvieto",
  "Macerata Feltria",
  "Mercatello sul Metauro",
  "Mercatino Conca",
  "Mombaroccio",
  "Mondavio",
  "Mondolfo",
  "Montecalvo in Foglia",
  "Monte Cerignone",
  "Montefelcino",
  "Monte Grimano Terme",
  "Montelabbate",
  "Monte Porzio",
  "Maiolati Spontini",
  "Mergo",
  "Monsano",
  "Montecarotto",
  "Montemarciano",
  "Monte Roberto",
  "Monte San Vito",
  "Morro d'Alba",
  "Macerata",
  "Matelica",
  "Mogliano",
  "Montecassiano",
  "Monte Cavallo",
  "Montecosaro",
  "Montefano",
  "Montelupone",
  "Monte San Giusto",
  "Monte San Martino",
  "Morrovalle",
  "Muccia",
  "Maltignano",
  "Massignano",
  "Monsampolo del Tronto",
  "Montalto delle Marche",
  "Montedinove",
  "Montefiore dell'Aso",
  "Montegallo",
  "Montemonaco",
  "Monteprandone",
  "Magliano di Tenna",
  "Massa Fermana",
  "Monsampietro Morico",
  "Montappone",
  "Montefalcone Appennino",
  "Montefortino",
  "Monte Giberto",
  "Montegiorgio",
  "Montegranaro",
  "Monteleone di Fermo",
  "Montelparo",
  "Monte Rinaldo",
  "Monterubbiano",
  "Monte San Pietrangeli",
  "Monte Urano",
  "Monte Vidon Combatte",
  "Monte Vidon Corrado",
  "Montottone",
  "Moresco",
  "Marta",
  "Montalto di Castro",
  "Montefiascone",
  "Monte Romano",
  "Monterosi",
  "Magliano Sabina",
  "Marcetelli",
  "Micigliano",
  "Mompeo",
  "Montasola",
  "Montebuono",
  "Monteleone Sabino",
  "Montenero Sabino",
  "Monte San Giovanni in Sabina",
  "Montopoli di Sabina",
  "Morro Reatino",
  "Magliano Romano",
  "Mandela",
  "Manziana",
  "Marano Equo",
  "Marcellina",
  "Marino",
  "Mazzano Romano",
  "Mentana",
  "Monte Compatri",
  "Monteflavio",
  "Montelanico",
  "Montelibretti",
  "Monte Porzio Catone",
  "Monterotondo",
  "Montorio Romano",
  "Moricone",
  "Morlupo",
  "Maenza",
  "Minturno",
  "Monte San Biagio",
  "Monte San Giovanni Campano",
  "Morolo",
  "Magliano de' Marsi",
  "Massa d'Albe",
  "Molina Aterno",
  "Montereale",
  "Morino",
  "Montefino",
  "Montorio al Vomano",
  "Morro d'Oro",
  "Mosciano Sant'Angelo",
  "Martinsicuro",
  "Manoppello",
  "Montebello di Bertona",
  "Montesilvano",
  "Moscufo",
  "Montebello sul Sangro",
  "Miglianico",
  "Montazzoli",
  "Monteferrante",
  "Montelapiano",
  "Montenerodomo",
  "Monteodorisio",
  "Mozzagrogna",
  "Macchia Valfortore",
  "Mafalda",
  "Matrice",
  "Mirabello Sannitico",
  "Molise",
  "Monacilioni",
  "Montagano",
  "Montecilfone",
  "Montefalcone nel Sannio",
  "Montelongo",
  "Montemitro",
  "Montenero di Bisaccia",
  "Montorio nei Frentani",
  "Morrone del Sannio",
  "Macchia d'Isernia",
  "Macchiagodena",
  "Miranda",
  "Montaquila",
  "Montenero Val Cocchiara",
  "Monteroduni",
  "Macerata Campania",
  "Maddaloni",
  "Marcianise",
  "Marzano Appio",
  "Mignano Monte Lungo",
  "Mondragone",
  "Melizzano",
  "Moiano",
  "Molinara",
  "Montefalcone di Val Fortore",
  "Montesarchio",
  "Morcone",
  "Marano di Napoli",
  "Mariglianella",
  "Marigliano",
  "Massa Lubrense",
  "Melito di Napoli",
  "Meta",
  "Monte di Procida",
  "Mugnano di Napoli",
  "Massa di Somma",
  "Manocalzati",
  "Marzano di Nola",
  "Melito Irpino",
  "Mercogliano",
  "Mirabella Eclano",
  "Montaguto",
  "Montecalvo Irpino",
  "Montefalcione",
  "Monteforte Irpino",
  "Montefredane",
  "Montefusco",
  "Montella",
  "Montemarano",
  "Montemiletto",
  "Monteverde",
  "Morra De Sanctis",
  "Moschiano",
  "Mugnano del Cardinale",
  "Montoro",
  "Magliano Vetere",
  "Maiori",
  "Mercato San Severino",
  "Minori",
  "Moio della Civitella",
  "Montano Antilia",
  "Montecorice",
  "Montecorvino Pugliano",
  "Montecorvino Rovella",
  "Monteforte Cilento",
  "Monte San Giacomo",
  "Montesano sulla Marcellana",
  "Morigerati",
  "Manfredonia",
  "Mattinata",
  "Monteleone di Puglia",
  "Monte Sant'Angelo",
  "Motta Montecorvino",
  "Modugno",
  "Mola di Bari",
  "Molfetta",
  "Monopoli",
  "Manduria",
  "Martina Franca",
  "Maruggio",
  "Massafra",
  "Monteiasi",
  "Montemesola",
  "Monteparano",
  "Mottola",
  "Mesagne",
  "Maglie",
  "Martano",
  "Martignano",
  "Matino",
  "Melendugno",
  "Melissano",
  "Melpignano",
  "Miggiano",
  "Minervino di Lecce",
  "Monteroni di Lecce",
  "Montesano Salentino",
  "Morciano di Leuca",
  "Muro Leccese",
  "Margherita di Savoia",
  "Minervino Murge",
  "Maratea",
  "Marsico Nuovo",
  "Marsicovetere",
  "Maschito",
  "Melfi",
  "Missanello",
  "Moliterno",
  "Montemilone",
  "Montemurro",
  "Muro Lucano",
  "Matera",
  "Miglionico",
  "Montalbano Jonico",
  "Montescaglioso",
  "Maier\u00e0",
  "Malito",
  "Malvito",
  "Mandatoriccio",
  "Mangone",
  "Marano Marchesato",
  "Marano Principato",
  "Marzi",
  "Mendicino",
  "Mongrassano",
  "Montalto Uffugo",
  "Montegiordano",
  "Morano Calabro",
  "Mormanno",
  "Mottafollone",
  "Magisano",
  "Maida",
  "Marcedusa",
  "Marcellinara",
  "Martirano",
  "Martirano Lombardo",
  "Miglierina",
  "Montauro",
  "Montepaone",
  "Motta Santa Lucia",
  "Mammola",
  "Marina di Gioiosa Ionica",
  "Maropati",
  "Martone",
  "Melicucc\u00e0",
  "Melicucco",
  "Melito di Porto Salvo",
  "Molochio",
  "Monasterace",
  "Montebello Jonico",
  "Motta San Giovanni",
  "Melissa",
  "Mesoraca",
  "Maierato",
  "Mileto",
  "Mongiana",
  "Monterosso Calabro",
  "Marsala",
  "Mazara del Vallo",
  "Misiliscemi",
  "Marineo",
  "Mezzojuso",
  "Misilmeri",
  "Monreale",
  "Montelepre",
  "Montemaggiore Belsito",
  "Malfa",
  "Malvagna",
  "Mandanici",
  "Mazzarr\u00e0 Sant'Andrea",
  "Mer\u00ec",
  "Messina",
  "Milazzo",
  "Militello Rosmarino",
  "Mirto",
  "Mistretta",
  "Moio Alcantara",
  "Monforte San Giorgio",
  "Mongiuffi Melia",
  "Montagnareale",
  "Montalbano Elicona",
  "Motta Camastra",
  "Motta d'Affermo",
  "Menfi",
  "Montallegro",
  "Montevago",
  "Marianopoli",
  "Mazzarino",
  "Milena",
  "Montedoro",
  "Mussomeli",
  "Maletto",
  "Mascali",
  "Mascalucia",
  "Militello in Val di Catania",
  "Milo",
  "Mineo",
  "Mirabella Imbaccari",
  "Misterbianco",
  "Motta Sant'Anastasia",
  "Mazzarrone",
  "Maniace",
  "Modica",
  "Monterosso Almo",
  "Melilli",
  "Mara",
  "Martis",
  "Monteleone Rocca Doria",
  "Monti",
  "Mores",
  "Muros",
  "Macomer",
  "Mamoiada",
  "Meana Sardo",
  "Maracalagonis",
  "Monserrato",
  "Marrubiu",
  "Masullas",
  "Milis",
  "Mogorella",
  "Mogoro",
  "Morgongiori",
  "Magomadas",
  "Modolo",
  "Montresta",
  "Mandas",
  "Masainas",
  "Monastir",
  "Muravera",
  "Musei",
];
